import React, { useState } from 'react';
import { ArrowRight, BookOpen, Users, Sparkles } from 'lucide-react';
import { supabase } from '../lib/supabase';

export default function Auth() {
  const [isLogin, setIsLogin] = useState(true); const [loading, setLoading] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  async function submit(e) { e.preventDefault(); setLoading(true); setError(''); setMessage(''); const f = new FormData(e.currentTarget); const email = String(f.get('email') || ''); const password = String(f.get('password') || ''); if (!supabase) { setError('Supabase is not configured. Add the required environment variables before using authentication.'); setLoading(false); return; } const result = isLogin ? await supabase.auth.signInWithPassword({ email, password }) : await supabase.auth.signUp({ email, password, options: { data: { full_name: f.get('full_name'), username: f.get('username') } } }); if (result.error) setError(result.error.message); else if (!isLogin && !result.data.session) setMessage('Account created. Check your email to confirm your address.'); setLoading(false); }
  return <div className="auth-page"><div className="auth-card"><div className="brand auth-brand"><span className="logo-mark">A</span><span>ADUSTECH <b>Connect</b></span></div><div className="auth-copy"><div className="eyebrow">MEET · CONNECT · BELONG</div><h1>{isLogin ? 'Welcome back.' : 'Create your account.'}</h1><p>Discover students, study partners and communities across ADUSTECH.</p></div><div className="auth-tabs"><button className={isLogin ? 'active' : ''} onClick={() => setIsLogin(true)}>Log in</button><button className={!isLogin ? 'active' : ''} onClick={() => setIsLogin(false)}>Sign up</button></div>{error && <div className="error-box">{error}</div>}{message && <div className="success-box">{message}</div>}<form onSubmit={submit}>{!isLogin && <><label>Full name<input name="full_name" required autoComplete="name" /></label><label>Username<input name="username" required minLength="3" autoComplete="username" /></label></>}<label>Email<input type="email" name="email" required autoComplete="email" /></label><label>Password<input type="password" name="password" required minLength="8" autoComplete={isLogin ? 'current-password' : 'new-password'} /></label><button className="btn btn-primary full" disabled={loading}>{loading ? 'Please wait…' : isLogin ? 'Log in' : 'Create account'}<ArrowRight size={17} /></button></form><div className="auth-features"><span><Users size={16} /> Student-first</span><span><BookOpen size={16} /> Study together</span><span><Sparkles size={16} /> Private by design</span></div><p className="disclaimer">Independent platform. Not officially affiliated with or endorsed by ADUSTECH.</p></div></div>;
}
